### ISSUE TITLE
Images not loading - giving error

### ISSUE THREAD

**Issue by DeveloperMCD** [shelajev/Retrofit2SampleApp#3]
At first, I was getting this error:
Error:Execution failed for task ':app:transformNative_libsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi-v7a/libblasV8.so
  	File1: /home/matthew/dev/java/Retrofit2SampleApp/app/build/intermediates/exploded-aar/jp.wasabeef/picasso-transformations/1.3.1/jni
  	File2: /home/matthew/dev/java/Retrofit2SampleApp/app/build/intermediates/exploded-aar/jp.wasabeef/glide-transformations/1.3.1/jni
  	File3: /home/matthew/dev/java/Retrofit2SampleApp/app/build/intermediates/exploded-aar/jp.wasabeef/fresco-processors/1.1.1/jni

Then I put this in my build.gradle
    packagingOptions {
        exclude 'lib/mips/librsjni.so'
        exclude 'lib/x86/librsjni.so'
        exclude 'lib/armeabi-v7a/librsjni.so'
        exclude 'lib/mips/libblasV8.so'
        exclude 'lib/x86/libblasV8.so'
        exclude 'lib/armeabi-v7a/libblasV8.so'
        exclude 'lib/x86/libRSSupport.so'
        exclude 'lib/mips/libRSSupport.so'
        exclude 'lib/armeabi-v7a/libRSSupport.so'
    }

But then, even though it compiles OK, I still can't view any of the images. It might be because I excluded all the .so files above?

D/OkHttp: X-Served-By: 173530fed4bbeb1e264b2ed22e8b5c20
D/OkHttp: X-GitHub-Request-Id: 42D41E92:25EE2:484E9B8:586EAABE
D/OkHttp: [{"login":"toomasr","id":196499,"avatar_url":"https://avatars.githubusercontent.com/u/196499?v=3","gravatar_id":"","url":"https://api.github.com/users/toomasr","html_url":"https://github.com/toomasr","followers_url":"https://api.github.com/users/toomasr/followers","following_url":"https://api.github.com/users/toomasr/following{/other_user}","gists_url":"https://api.github.com/users/toomasr/gists{/gist_id}","starred_url":"https://api.github.com/users/toomasr/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/toomasr/subscriptions","organizations_url":"https://api.github.com/users/toomasr/orgs","repos_url":"https://api.github.com/users/toomasr/repos","events_url":"https://api.github.com/users/toomasr/events{/privacy}","received_events_url":"https://api.github.com/users/toomasr/received_events","type":"User","site_admin":false,"contributions":153},{"login":"shelajev","id":426039,"avatar_url":"https://avatars.githubusercontent.com/u/426039?v=3","gravatar_id":"","url":"https://api.github.com/users/shelajev","html_url":"https://github.com/shelajev","followers_url":"https://api.github.com/users/shelajev/followers","following_url":"https://api.github.com/users/shelajev/following{/other_user}","gists_url":"https://api.github.com/users/shelajev/gists{/gist_id}","starred_url":"https://api.github.com/users/shelajev/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/shelajev/subscriptions","organizations_url":"https://api.github.com/users/shelajev/orgs","repos_url":"https://api.github.com/users/shelajev/repos","events_url":"https://api.github.com/users/shelajev/events{/privacy}","received_events_url":"https://api.github.com/users/shelajev/received_events","type":"User","site_admin":false,"contributions":56},{"login":"reinra","id":790553,"avatar_url":"https://avatars.githubusercontent.com/u/790553?v=3","gravatar_id":"","url":"https://api.github.com/users/reinra","html_url":"https://github.com/reinra","followers_url":"https://api.github.com/users/reinra/followers","following_url":"https://api.github.com/users/reinra/following{/other_user}","gists_url":"https://api.github.com/users/reinra/gists{/gist_id}","starred_url":"https://api.github.com/users/reinra/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/reinra/subscriptions","organizations_url":"https://api.github.com/users/reinra/orgs","repos_url":"https://api.github.com/users/reinra/repos","events_url":"https://api.github.com/users/reinra/events{/privacy}","received_events_url":"https://api.github.com/users/reinra/received_events","type":"User","site_admin":false,"contributions":38},{"login":"nemecec","id":1180780,"avatar_url":"https://avatars.githubusercontent.com/u/1180780?v=3","gravatar_id":"","url":"https://api.github.com/users/nemecec","html_url":"https://github.com/nemecec","followers_url":"https://api.github.com/users/nemecec/followers","following_url":"https://api.github.com/users/nemecec/following{/other_user}","gists_url":"https://api.github.com/users/nemecec/gists{/gist_id}","starred_url":"https://api.github.com/users/nemecec/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/nemecec/subscriptions","organizations_url":"https://api.github.com/users/nemecec/orgs","repos_url":"https://api.github.com/users/nemecec/repos","events_url":"https://api.github.com/users/nemecec/events{/privacy}","received_events_url":"https://api.github.com/users/nemecec/received_events","type":"User","site_admin":false,"contributions":33},{"login":"cordje","id":1800281,"avatar_url":"https://avatars.githubusercontent.com/u/1800281?v=3","gravatar_id":"","url":"https://api.github.com/users/cordje","html_url":"https://github.com/cordje","followers_url":"https://api.github.com/users/cordje/followers","following_url":"https://api.github.com/users/cordje/following{/other_user}","gists_url":"https://api.github.com/users/cordje/gists{/gist_id}","starred_url":"https://api.github.com/users/cordje/starred{/owner}{/repo}","sub
D/OkHttp: scriptions_url":"https://api.github.com/users/cordje/subscriptions","organizations_url":"https://api.github.com/users/cordje/orgs","repos_url":"https://api.github.com/users/cordje/repos","events_url":"https://api.github.com/users/cordje/events{/privacy}","received_events_url":"https://api.github.com/users/cordje/received_events","type":"User","site_admin":false,"contributions":6},{"login":"atsuiboupin","id":1336334,"avatar_url":"https://avatars.githubusercontent.com/u/1336334?v=3","gravatar_id":"","url":"https://api.github.com/users/atsuiboupin","html_url":"https://github.com/atsuiboupin","followers_url":"https://api.github.com/users/atsuiboupin/followers","following_url":"https://api.github.com/users/atsuiboupin/following{/other_user}","gists_url":"https://api.github.com/users/atsuiboupin/gists{/gist_id}","starred_url":"https://api.github.com/users/atsuiboupin/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/atsuiboupin/subscriptions","organizations_url":"https://api.github.com/users/atsuiboupin/orgs","repos_url":"https://api.github.com/users/atsuiboupin/repos","events_url":"https://api.github.com/users/atsuiboupin/events{/privacy}","received_events_url":"https://api.github.com/users/atsuiboupin/received_events","type":"User","site_admin":false,"contributions":6},{"login":"antonarhipov","id":177047,"avatar_url":"https://avatars.githubusercontent.com/u/177047?v=3","gravatar_id":"","url":"https://api.github.com/users/antonarhipov","html_url":"https://github.com/antonarhipov","followers_url":"https://api.github.com/users/antonarhipov/followers","following_url":"https://api.github.com/users/antonarhipov/following{/other_user}","gists_url":"https://api.github.com/users/antonarhipov/gists{/gist_id}","starred_url":"https://api.github.com/users/antonarhipov/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/antonarhipov/subscriptions","organizations_url":"https://api.github.com/users/antonarhipov/orgs","repos_url":"https://api.github.com/users/antonarhipov/repos","events_url":"https://api.github.com/users/antonarhipov/events{/privacy}","received_events_url":"https://api.github.com/users/antonarhipov/received_events","type":"User","site_admin":false,"contributions":5},{"login":"andrus7k","id":1029078,"avatar_url":"https://avatars.githubusercontent.com/u/1029078?v=3","gravatar_id":"","url":"https://api.github.com/users/andrus7k","html_url":"https://github.com/andrus7k","followers_url":"https://api.github.com/users/andrus7k/followers","following_url":"https://api.github.com/users/andrus7k/following{/other_user}","gists_url":"https://api.github.com/users/andrus7k/gists{/gist_id}","starred_url":"https://api.github.com/users/andrus7k/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/andrus7k/subscriptions","organizations_url":"https://api.github.com/users/andrus7k/orgs","repos_url":"https://api.github.com/users/andrus7k/repos","events_url":"https://api.github.com/users/andrus7k/events{/privacy}","received_events_url":"https://api.github.com/users/andrus7k/received_events","type":"User","site_admin":false,"contributions":5},{"login":"MastaP","id":185344,"avatar_url":"https://avatars.githubusercontent.com/u/185344?v=3","gravatar_id":"","url":"https://api.github.com/users/MastaP","html_url":"https://github.com/MastaP","followers_url":"https://api.github.com/users/MastaP/followers","following_url":"https://api.github.com/users/MastaP/following{/other_user}","gists_url":"https://api.github.com/users/MastaP/gists{/gist_id}","starred_url":"https://api.github.com/users/MastaP/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/MastaP/subscriptions","organizations_url":"https://api.github.com/users/MastaP/orgs","repos_url":"https://api.github.com/users/MastaP/repos","events_url":"https://api.github.com/users/MastaP/events{/privacy}","received_events_url":"https://api.github.com/users/MastaP/received_events","type":"User","site_admin":false,"contributions":
D/OkHttp: 3},{"login":"romanzes","id":5735967,"avatar_url":"https://avatars.githubusercontent.com/u/5735967?v=3","gravatar_id":"","url":"https://api.github.com/users/romanzes","html_url":"https://github.com/romanzes","followers_url":"https://api.github.com/users/romanzes/followers","following_url":"https://api.github.com/users/romanzes/following{/other_user}","gists_url":"https://api.github.com/users/romanzes/gists{/gist_id}","starred_url":"https://api.github.com/users/romanzes/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/romanzes/subscriptions","organizations_url":"https://api.github.com/users/romanzes/orgs","repos_url":"https://api.github.com/users/romanzes/repos","events_url":"https://api.github.com/users/romanzes/events{/privacy}","received_events_url":"https://api.github.com/users/romanzes/received_events","type":"User","site_admin":false,"contributions":2},{"login":"Flet","id":360233,"avatar_url":"https://avatars.githubusercontent.com/u/360233?v=3","gravatar_id":"","url":"https://api.github.com/users/Flet","html_url":"https://github.com/Flet","followers_url":"https://api.github.com/users/Flet/followers","following_url":"https://api.github.com/users/Flet/following{/other_user}","gists_url":"https://api.github.com/users/Flet/gists{/gist_id}","starred_url":"https://api.github.com/users/Flet/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Flet/subscriptions","organizations_url":"https://api.github.com/users/Flet/orgs","repos_url":"https://api.github.com/users/Flet/repos","events_url":"https://api.github.com/users/Flet/events{/privacy}","received_events_url":"https://api.github.com/users/Flet/received_events","type":"User","site_admin":false,"contributions":2},{"login":"mjomble","id":2202751,"avatar_url":"https://avatars.githubusercontent.com/u/2202751?v=3","gravatar_id":"","url":"https://api.github.com/users/mjomble","html_url":"https://github.com/mjomble","followers_url":"https://api.github.com/users/mjomble/followers","following_url":"https://api.github.com/users/mjomble/following{/other_user}","gists_url":"https://api.github.com/users/mjomble/gists{/gist_id}","starred_url":"https://api.github.com/users/mjomble/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/mjomble/subscriptions","organizations_url":"https://api.github.com/users/mjomble/orgs","repos_url":"https://api.github.com/users/mjomble/repos","events_url":"https://api.github.com/users/mjomble/events{/privacy}","received_events_url":"https://api.github.com/users/mjomble/received_events","type":"User","site_admin":false,"contributions":1},{"login":"dkatona","id":822447,"avatar_url":"https://avatars.githubusercontent.com/u/822447?v=3","gravatar_id":"","url":"https://api.github.com/users/dkatona","html_url":"https://github.com/dkatona","followers_url":"https://api.github.com/users/dkatona/followers","following_url":"https://api.github.com/users/dkatona/following{/other_user}","gists_url":"https://api.github.com/users/dkatona/gists{/gist_id}","starred_url":"https://api.github.com/users/dkatona/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dkatona/subscriptions","organizations_url":"https://api.github.com/users/dkatona/orgs","repos_url":"https://api.github.com/users/dkatona/repos","events_url":"https://api.github.com/users/dkatona/events{/privacy}","received_events_url":"https://api.github.com/users/dkatona/received_events","type":"User","site_admin":false,"contributions":1},{"login":"gbevin","id":701148,"avatar_url":"https://avatars.githubusercontent.com/u/701148?v=3","gravatar_id":"","url":"https://api.github.com/users/gbevin","html_url":"https://github.com/gbevin","followers_url":"https://api.github.com/users/gbevin/followers","following_url":"https://api.github.com/users/gbevin/following{/other_user}","gists_url":"https://api.github.com/users/gbevin/gists{/gist_id}","starred_url":"https://api.github.com/users/gbevin/starred{/owner}{/repo}","subscriptions_url":"https://ap
D/OkHttp: i.github.com/users/gbevin/subscriptions","organizations_url":"https://api.github.com/users/gbevin/orgs","repos_url":"https://api.github.com/users/gbevin/repos","events_url":"https://api.github.com/users/gbevin/events{/privacy}","received_events_url":"https://api.github.com/users/gbevin/received_events","type":"User","site_admin":false,"contributions":1},{"login":"Nowheresly","id":916109,"avatar_url":"https://avatars.githubusercontent.com/u/916109?v=3","gravatar_id":"","url":"https://api.github.com/users/Nowheresly","html_url":"https://github.com/Nowheresly","followers_url":"https://api.github.com/users/Nowheresly/followers","following_url":"https://api.github.com/users/Nowheresly/following{/other_user}","gists_url":"https://api.github.com/users/Nowheresly/gists{/gist_id}","starred_url":"https://api.github.com/users/Nowheresly/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Nowheresly/subscriptions","organizations_url":"https://api.github.com/users/Nowheresly/orgs","repos_url":"https://api.github.com/users/Nowheresly/repos","events_url":"https://api.github.com/users/Nowheresly/events{/privacy}","received_events_url":"https://api.github.com/users/Nowheresly/received_events","type":"User","site_admin":false,"contributions":1}]
D/OkHttp: <-- END HTTP (13269-byte body)
E/RenderScript_jni: Error loading RS jni library: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-support-annotations-25.1.0_26864a74d953770b335beb8d827e8f4ebe779157-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-retrofit-2.0.0-beta4_553fa874e0597afdb041d6efe30cf9ab9015cf9b-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-renderscript-v8_ab4c6bc276ebf8285f9673b21f4273b94254532b-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-picasso-2.5.2_05ac6c64f15f46f68087d52f7ba331110d4c204b-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-parceler-api-1.1.6_d95ecb9eacf820713e84c8ad06a10dcbb07f6caf-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-okio-1.8.0_8248c52dc90fea34a36fec3adcf69c8bd1421020-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-okhttp-3.3.1_a487d4e59b3d8c00968fad84d9bb51b0cdb35bba-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-logging-interceptor-3.3.1_dc8658a5e9a32dd98e86100878e020c7372c214f-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-library-2.4.0_80fca63f7f80f83dd77f94de4757132a1e9e9e9a-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-jp.wasabeef-picasso-transformations-1.3.1_579ae0acd23944d8fbf3ff12fd9839a70442b92e-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-jp.wasabeef-glide-transformations-1.3.1_c1db208994ad53623b38e2306d58a2ae5a2adaad-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-jp.wasabeef-fresco-processors-1.1.1_f48584d83b65a2ea6cb130d81a454f6167c0bef6-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-icepick-3.2.0_38d9985dbfc9baa6a27a5f648ea406ad6ed180b8-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-henson-2.0.1_a832850d615eed948cc1af6dbb82a861c02c7d87-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-gson-2.4_c9b32c097189d463121e7dc2ea39e4bdf9e8bb62-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-glide-3.7.0_78d9ce16250d4803b6d63cd6e54994a0ca1a6492-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-dart-annotations-2.0.1_9b878163479210f0e5c7fb60a6f7bef81678fa1e-classes.dex", dex file "/data/data/org.zeroturnaround.githubco
E/System: Uncaught exception thrown by finalizer
E/System: android.support.v8.renderscript.RSInvalidStateException: Calling RS with no Context active.
              at android.support.v8.renderscript.RenderScript.validate(RenderScript.java:1225)
              at android.support.v8.renderscript.RenderScript.nContextFinish(RenderScript.java:320)
              at android.support.v8.renderscript.RenderScript.helpDestroy(RenderScript.java:1657)
              at android.support.v8.renderscript.RenderScript.finalize(RenderScript.java:1691)
              at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
              at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
              at java.lang.Thread.run(Thread.java:761)
E/RenderScript_jni: Error loading RS jni library: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-support-annotations-25.1.0_26864a74d953770b335beb8d827e8f4ebe779157-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-retrofit-2.0.0-beta4_553fa874e0597afdb041d6efe30cf9ab9015cf9b-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-renderscript-v8_ab4c6bc276ebf8285f9673b21f4273b94254532b-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-picasso-2.5.2_05ac6c64f15f46f68087d52f7ba331110d4c204b-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-parceler-api-1.1.6_d95ecb9eacf820713e84c8ad06a10dcbb07f6caf-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-okio-1.8.0_8248c52dc90fea34a36fec3adcf69c8bd1421020-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-okhttp-3.3.1_a487d4e59b3d8c00968fad84d9bb51b0cdb35bba-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-logging-interceptor-3.3.1_dc8658a5e9a32dd98e86100878e020c7372c214f-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-library-2.4.0_80fca63f7f80f83dd77f94de4757132a1e9e9e9a-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-jp.wasabeef-picasso-transformations-1.3.1_579ae0acd23944d8fbf3ff12fd9839a70442b92e-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-jp.wasabeef-glide-transformations-1.3.1_c1db208994ad53623b38e2306d58a2ae5a2adaad-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-jp.wasabeef-fresco-processors-1.1.1_f48584d83b65a2ea6cb130d81a454f6167c0bef6-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-icepick-3.2.0_38d9985dbfc9baa6a27a5f648ea406ad6ed180b8-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-henson-2.0.1_a832850d615eed948cc1af6dbb82a861c02c7d87-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-gson-2.4_c9b32c097189d463121e7dc2ea39e4bdf9e8bb62-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-glide-3.7.0_78d9ce16250d4803b6d63cd6e54994a0ca1a6492-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-dart-annotations-2.0.1_9b878163479210f0e5c7fb60a6f7bef81678fa1e-classes.dex", dex file "/data/data/org.zeroturnaround.githubco
E/RenderScript_jni: Error loading RS jni library: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-support-annotations-25.1.0_26864a74d953770b335beb8d827e8f4ebe779157-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-retrofit-2.0.0-beta4_553fa874e0597afdb041d6efe30cf9ab9015cf9b-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-renderscript-v8_ab4c6bc276ebf8285f9673b21f4273b94254532b-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-picasso-2.5.2_05ac6c64f15f46f68087d52f7ba331110d4c204b-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-parceler-api-1.1.6_d95ecb9eacf820713e84c8ad06a10dcbb07f6caf-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-okio-1.8.0_8248c52dc90fea34a36fec3adcf69c8bd1421020-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-okhttp-3.3.1_a487d4e59b3d8c00968fad84d9bb51b0cdb35bba-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-logging-interceptor-3.3.1_dc8658a5e9a32dd98e86100878e020c7372c214f-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-library-2.4.0_80fca63f7f80f83dd77f94de4757132a1e9e9e9a-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-jp.wasabeef-picasso-transformations-1.3.1_579ae0acd23944d8fbf3ff12fd9839a70442b92e-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-jp.wasabeef-glide-transformations-1.3.1_c1db208994ad53623b38e2306d58a2ae5a2adaad-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-jp.wasabeef-fresco-processors-1.1.1_f48584d83b65a2ea6cb130d81a454f6167c0bef6-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-icepick-3.2.0_38d9985dbfc9baa6a27a5f648ea406ad6ed180b8-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-henson-2.0.1_a832850d615eed948cc1af6dbb82a861c02c7d87-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-gson-2.4_c9b32c097189d463121e7dc2ea39e4bdf9e8bb62-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-glide-3.7.0_78d9ce16250d4803b6d63cd6e54994a0ca1a6492-classes.dex", dex file "/data/data/org.zeroturnaround.githubcontributors/files/instant-run/dex/slice-dart-annotations-2.0.1_9b878163479210f0e5c7fb60a6f7bef81678fa1e-classes.dex", dex file "/data/data/org.zeroturnaround.githubco
E/System: Uncaught exception thrown by finalizer
E/System: android.support.v8.renderscript.RSInvalidStateException: Calling RS with no Context active.
              at android.support.v8.renderscript.RenderScript.validate(RenderScript.java:1225)
              at android.support.v8.renderscript.RenderScript.nContextFinish(RenderScript.java:320)
              at android.support.v8.renderscript.RenderScript.helpDestroy(RenderScript.java:1657)
              at android.support.v8.renderscript.RenderScript.finalize(RenderScript.java:1691)
              at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:222)
              at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:209)
              at java.lang.Thread.run(Thread.java:761)
E/System: Uncaught exception thrown by finalizer

**Comment by sten711** [comment]
Should be fixed now. Looks like the latest build tools won't allow duplicate .so files in the apk anymore. Picasso and Glide were moved to separate product flavors as the transformation library used the same .so files.

**Comment by shelajev** [comment]
Thanks, @DeveloperMCD for uncovering this issue and, @sten711 for fixing it.
